apiVersion: v1
kind: Service
metadata:
  name: velero-metrics
  namespace: velero
  labels:
    app.kubernetes.io/name: velero
spec:
  ports:
    - name: metrics
      port: 8085
      targetPort: 8085
  selector:
    component: velero
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: velero
  namespace: velero
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: velero  # ⬅ HAT DER SERVICE!
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
