---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-server
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: code-server
  template:
    metadata:
      labels:
        app: code-server
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: code-server
          image: codercom/code-server:latest
          imagePullPolicy: Always
          env:
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: code-server-secret
                  key: password
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            - name: data
              mountPath: /home/toadie
            - name: config
              mountPath: /home/toadie/.config
          resources:
            requests:
              memory: 512Mi
              cpu: 250m
            limits:
              memory: 2Gi
              cpu: 1500m
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: code-server-data
        - name: config
          emptyDir: {}
