apiVersion: v1
kind: Pod
metadata:
  name: nfs-test-app
spec:
  containers:
  - name: test
    image: busybox:stable
    command: ["sleep", "infinity"]
    volumeMounts:
    - name: nfs-data
      mountPath: /data
  volumes:
  - name: nfs-data
    persistentVolumeClaim:
      claimName: nfs-test
#  nodeSelector:
#    kubernetes.io/hostname: worker02
