server:
  assets-path: /app/assets
#theme:
# Note: assets are cached by the browser, changes to the CSS file
# will not be reflected until the browser cache is cleared (Ctrl+F5)
#  custom-css-file: /assets/user.css
theme:
  background-color: 227 11 16
  contrast-multiplier: 1.2
  primary-color: 220 34 51
  positive-color: 136 53 43
  negative-color: 5 81 56
pages:
  # It's not necessary to create a new file for each page and include it, you can simply
  # put its contents here, though multiple pages are easier to manage when separated
  - $include: dashboard.yml
  - $include: teste2.yml
  - $include: kubernetes.yml
  - $include: test.yml
