[pi_cluster]
#winterfell ansible_host=192.168.178.210 ansible_user=toadie ansible_ssh_private_key_file=~/.ssh/id_ed25519
winterfell ansible_host=192.168.178.210 ansible_user=toadie
worker01 ansible_host=192.168.178.212
worker02 ansible_host=192.168.178.214

[k3s_master]
winterfell

[k3s_workers]
worker01
worker02
