apiVersion: v1
kind: Pod
metadata:
  name: alpine-test
spec:
  containers:
  - name: alpine
    image: alpine:latest
    command: ["sleep", "infinity"]
    resources:
      limits:
        memory: "128Mi"
        cpu: "250m"
  restartPolicy: Never
