[global]
   workgroup = POLYGON
   server string = %h server Linux Mint
   dns proxy = no
   netbios name = toadlap
   log file = /var/log/samba/log.%m
   max log size = 1000
   syslog = 0
   panic action = /usr/share/samba/panic-action %d
   security = user
   encrypt passwords = true
   passdb backend = tdbsam
   obey pam restrictions = yes
   unix password sync = yes
   passwd program = /usr/bin/passwd %u
   passwd chat = *Enter\snew\s*\spassword:* %n\n *Retype\snew\s*\spassword:* %n\n *password\supdated\ssuccessfully* .
   pam password change = yes
   map to guest = bad user
   usershare max shares = 100
[toadie]
   comment = home of toadie
   path = /home/toadie
   guest ok = no
   read only = no
   share modes = no
   browseable = yes
[DATA]
   comment = DATA
   path = /media/DATA
   guest ok = no
   read only = no
   share modes = no
   browseable = yes
