#======================= Global Settings =======================

[global]
workgroup = POLYGON
server string = toad
#   wins support = no
#   wins server = w.x.y.z
#  dns proxy = no
;   name resolve order = lmhosts host wins bcast
netbios name = toad

#### Networking ####
interfaces = 127.0.0.0/8 eth1
;   bind interfaces only = yes

#### Debugging/Accounting ####
#   log file = /var/log/samba/log.%m
#   max log size = 1000
# parameter to 'yes'.
#   syslog only = no
   syslog = 0
   panic action = /usr/share/samba/panic-action %d

####### Authentication #######

security = user
encrypt passwords = true
passdb backend = tdbsam
obey pam restrictions = yes
unix password sync = yes
passwd program = /usr/bin/passwd %u
passwd chat = *Enter\snew\s*\spassword:* %n\n *Retype\snew\s*\spassword:* %n\n *password\supdated\ssuccessfully* .
pam password change = yes
map to guest = bad user
unix extensions = yes

############ Misc ############

#   usershare max shares = 100
#   usershare allow guests = yes

#======================= Share Definitions =======================

[toadie]
comment = home of toadie
writeable = yes
path = /home/toadie
browseable = yes
#   read only = yes
create mask = 0700
directory mask = 0700
valid users = toadie

[DATA]
comment = DATA
writeable = yes
path = /media/data
browseable = yes
guest ok = yes
valid users = toadie

